# create a playbook to install nginx web server on a web machine 
# web 192.168.33.10
# now with these 3 dashes it becomes a YAML file
---
# add the name of the host
- hosts: web
# gather facts 
  gather_facts: yes
# now we need admin access 
  become: true
# add instructions to install nginx on web machine 
# state present means that the package is running 
  tasks: 
  - name: Install Nginx
    apt: pkg=nginx state=present
# ensure the nginx server is running 
